export { ingestRaw, normalizeStaging, buildMarts, validateData, mapChannelFromOrder, mapGA4ChannelToSlug } from './pipeline/index.js';
export { generateAllDemoData, fetchShopifyOrders, fetchShopifyCustomers, fetchMetaInsights, fetchGoogleAdsInsights, fetchGA4Traffic, fetchTikTokInsights, fetchKlaviyoCampaigns, fetchKlaviyoFlows, fetchStripeCharges, fetchStripeRefunds } from './connectors/index.js';
export * as kpis from './kpis.js';
export { evaluateAlerts } from './alerts.js';
export type { Alert, AlertInput } from './alerts.js';
export type { ValidationResult } from './pipeline/validate.js';
export type { ShopifyConfig, MetaConfig, GoogleAdsConfig, GA4Config, TikTokConfig, KlaviyoConfig, StripeConfig, RawRecord } from './types.js';
export { forecast, forecastSeasonal } from './forecast.js';
export type { ForecastResult, ForecastConfig, SeasonalForecastConfig, SeasonalForecastResult } from './forecast.js';
export { detectSignals } from './signals.js';
export type { Signal, SignalInput, FunnelCvr } from './signals.js';
export { classifyOpportunities } from './opportunities.js';
export type { OpportunityCandidate, OpportunityType } from './opportunities.js';
export { computeGrowthModel, computeMonthlyBreakdown, DEMO_SCENARIOS } from './growth-model.js';
export type { GrowthModelInput, GrowthModelOutput, MonthlyProjection, DemoScenario } from './growth-model.js';
export { computeRFMScores, classifySegment, getSegmentDistribution } from './segmentation.js';
export type { CustomerRFM, RFMScores, CustomerSegment, SegmentSummary } from './segmentation.js';
export { seedDemoExperiments } from './demo-experiments.js';
