export { ingestRaw, normalizeStaging, buildMarts, buildProductPerformance, validateData, mapChannelFromOrder, mapGA4ChannelToSlug } from './pipeline/index.js';
export { generateAllDemoData, fetchShopifyOrders, fetchShopifyCustomers, fetchShopifyProducts, fetchMetaInsights, fetchGoogleAdsInsights, fetchGA4Traffic, fetchTikTokInsights, fetchKlaviyoCampaigns, fetchKlaviyoFlows, fetchStripeCharges, fetchStripeRefunds, generateShopifyProducts } from './connectors/index.js';
export { fetchMetaAdCreatives, generateDemoMetaAds, getCurrencyOffset } from './connectors/index.js';
export type { MetaAdCreativeConfig, MetaAdCreativeResult, MetaAccountInfo, MetaCampaignData, MetaAdSetData, MetaAdData, MetaAdInsight } from './connectors/index.js';
export * as kpis from './kpis.js';
export { evaluateAlerts } from './alerts.js';
export type { Alert, AlertInput } from './alerts.js';
export type { ValidationResult } from './pipeline/validate.js';
export type { ShopifyConfig, MetaConfig, GoogleAdsConfig, GA4Config, TikTokConfig, KlaviyoConfig, StripeConfig, RawRecord } from './types.js';
export { forecast, forecastSeasonal } from './forecast.js';
export type { ForecastResult, ForecastConfig, SeasonalForecastConfig, SeasonalForecastResult } from './forecast.js';
export { detectSignals } from './signals.js';
export type { Signal, SignalInput, FunnelCvr } from './signals.js';
export { classifyOpportunities } from './opportunities.js';
export type { OpportunityCandidate, OpportunityType } from './opportunities.js';
export { computeGrowthModel, computeMonthlyBreakdown, computeSafeSpendRange, DEMO_SCENARIOS } from './growth-model.js';
export type { GrowthModelInput, GrowthModelOutput, MonthlyProjection, DemoScenario, SafeSpendRange, SafeSpendConstraints } from './growth-model.js';
export { computeRFMScores, classifySegment, getSegmentDistribution } from './segmentation.js';
export type { CustomerRFM, RFMScores, CustomerSegment, SegmentSummary } from './segmentation.js';
export { seedDemoExperiments } from './demo-experiments.js';
export { seedDemoAutopilot } from './demo-autopilot.js';
export { seedDemoOpportunities } from './demo-opportunities.js';
export { evaluateDiagnosisRules } from './diagnosis-rules.js';
export type { DiagnosisRuleInput, DiagnosisResult, DiagnosisActionType, DiagnosisSeverityLevel, DiagnosisRuleConfig } from './diagnosis-rules.js';
export { computeDynamicThresholds } from './dynamic-thresholds.js';
export type { AdMetricsForThresholds, DynamicThresholds } from './dynamic-thresholds.js';
export { optimizeBudgetAllocation } from './budget-optimizer.js';
export type { AdSetMetrics, BudgetAllocation, BudgetOptimizerConfig, PortfolioOptimization } from './budget-optimizer.js';
export { analyzeCreativeDecay, linearRegression } from './creative-decay.js';
export type { DailySnapshot, CreativeDecayAnalysis, LinearRegressionResult } from './creative-decay.js';
export { scoreCampaignHealth } from './campaign-health.js';
export type { CampaignMetrics, AdSetHealth, CampaignHealthScore, CampaignHealthConfig } from './campaign-health.js';
export { detectAnomalies } from './anomaly-detection.js';
export type { MetricSeries, AnomalyResult, AnomalyDetectionConfig } from './anomaly-detection.js';
export { scoreAdFitness } from './product-scoring.js';
export type { AdFitnessInput, AdFitnessResult, AdFitnessBreakdown } from './product-scoring.js';
export { scoreDtcProduct } from './product-scoring-v2.js';
export type { DtcScoreInput, DtcScoreResult, DtcScoreBreakdown, CampaignRecommendation } from './product-scoring-v2.js';
export { evaluateProactiveRules } from './proactive-rules.js';
export type { ProductPerformanceRow, ProactiveRulesInput, ProactiveRecommendation } from './proactive-rules.js';
export { generateCampaignSuggestions } from './campaign-suggestions.js';
export type { CampaignSuggestion, CampaignSuggestionInput, ProductForCampaign } from './campaign-suggestions.js';
export { getUpcomingEvents, matchProductsToEvent, DEFAULT_SEASONAL_EVENTS } from './seasonal-calendar.js';
export type { SeasonalEvent } from './seasonal-calendar.js';
export { allocateBudget } from './budget-allocator.js';
export type { BudgetAllocationInput as CampaignBudgetAllocationInput, CampaignBudgetAllocation } from './budget-allocator.js';
export { selectTrigger, mapMetricToPsychSignal, inferAwarenessFromFunnel, TRIGGER_MATRIX, AWARENESS_LEVELS, EMOTIONAL_STATES, PSYCH_TRIGGERS } from './trigger-selection.js';
export type { AwarenessLevel, PsychTrigger, EmotionalState, FunnelStage, TriggerConfidenceLevel, TriggerPerformanceData, TriggerSelectionInput, TriggerRecommendation, PsychSignal } from './trigger-selection.js';
export { diagnosePsychology } from './psych-diagnostic.js';
export type { PsychDiagnosticInput, PsychDiagnosticNode, PsychDiagnosticCode, PsychBenchmarks } from './psych-diagnostic.js';
